### ISSUE TITLE
pip packages on windows have started failing

### ISSUE THREAD

**Issue by lefticus** [aminya/setup-cpp#27]
See here : https://github.com/lefticus/json2cpp/runs/5071314373?check_suite_focus=true#step:4:24

These packages were succeeded 2 days ago, failing now. I cannot tell what (if anything) changed in setup-cpp or github action configurations. I also don't see a meaningful message.

**Comment by aminya** [comment]
That's so strange. It is also happening on the master CI. 🤷‍♂️ 

Maybe related to this. It seems they have broken python
https://github.com/actions/virtual-environments/issues/5009

**Comment by lefticus** [comment]
Looks like it is fixed if you upgrade to setup-python 2.3.2 https://github.com/actions/setup-python/issues/328#issuecomment-1029945845 or just use `v2` tag so it gets the latest in v2.

**Comment by aminya** [comment]
@lefticus I updated v1 branch. Could you try this in another project? Maybe the issue is fixed, but my tests fail because of the environment.

**Comment by lefticus** [comment]
Same error still, it looks like it's still using the pip installed by github, instead of the one you are trying to use from chocolatey.

I'll fork this and see if I can learn anything.

**Comment by aminya** [comment]
Did you try manually adding setup-python before setup-cpp? 
```
- uses: actions/setup-python@v2
  with:
    python-version: '3.x'
```

**Comment by lefticus** [comment]
I did try that, and still get a failure. I haven't tried doing that and disabling your install of python

**Comment by aminya** [comment]
setup-cpp originally did not install pip if it found it pre-installed. But because the pre-installed pip3 is broken, I added this exception for windows to install it. However, it does not help, and pip3 is still broken. 
https://github.com/aminya/setup-cpp/blob/dabb2db00e118e54e5b00008d5bc2318b9f4b746/src/utils/setup/setupPipPack.ts#L21

**Comment by lefticus** [comment]
I can now confirm that if I manually install `setup-python@v2`, then `pip install gcovr conan` and disable setup-cpp's installation of gcovr and conan, then things work as expected.

That is, I have been able to isolate it to whatever setup-cpp is doing with pip.

https://github.com/lefticus/json2cpp/runs/5078807626?check_suite_focus=true#step:4:1

**Comment by aminya** [comment]
More reasons for this issue:

exec breakage: 
https://github.com/actions/toolkit/issues/992

pip breakage 
https://github.com/pypa/pip/issues/10875

**Comment by aminya** [comment]
Fixed in https://github.com/aminya/setup-cpp/commit/b7f10afb077bb6f3f9be8f105261a631226251b1
